# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file C ''
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_window(object):

    def setupUi(self, main_window) -> None:

        main_window.setObjectName("main_window")
        main_window.resize(600, 400)

        self.central_widget = QtWidgets.QWidget(main_window)
        self.central_widget.setObjectName("central_widget")
        main_window.setCentralWidget(self.central_widget)

        self.menu_bar = QtWidgets.QMenuBar(main_window)
        self.menu_bar.setGeometry(QtCore.QRect(0, 0, 600, 21))
        self.menu_bar.setObjectName("menu_bar")
        main_window.setMenuBar(self.menu_bar)

        self.menu_folder = QtWidgets.QMenu(self.menu_bar)
        self.menu_folder.setObjectName("menu_folder")

        self.menu_open = QtWidgets.QMenu(self.menu_folder)
        self.menu_open.setObjectName("menu_open")

        self.menu_edit = QtWidgets.QMenu(self.menu_bar)
        self.menu_edit.setObjectName("menu_edit")

        self.status_bar = QtWidgets.QStatusBar(main_window)
        self.status_bar.setObjectName("status_bar")
        main_window.setStatusBar(self.status_bar)

        self.action_save = QtWidgets.QAction(main_window)
        self.action_save.setObjectName("action_save")

        self.action_text = QtWidgets.QAction(main_window)
        self.action_text.setObjectName("action_text")

        self.menu_open.addAction(self.action_text)
        self.menu_folder.addAction(self.menu_open.menuAction())
        self.menu_folder.addAction(self.action_save)
        self.menu_bar.addAction(self.menu_folder.menuAction())
        self.menu_bar.addAction(self.menu_edit.menuAction())

        self.retranslateUi(main_window)

        QtCore.QMetaObject.connectSlotsByName(main_window)


    def retranslateUi(self, main_window) -> None:
        _translate = QtCore.QCoreApplication.translate

        main_window.setWindowTitle(_translate("main_window", "Main Window"))

        self.menu_folder.setTitle(_translate("main_window", "Folder"))
        self.menu_open.setTitle(_translate("main_window", "Open"))
        self.menu_edit.setTitle(_translate("main_window", "Edit"))

        self.action_save.setText(_translate("main_window", "Save"))
        self.action_save.setShortcut(_translate("main_window", "Ctrl+S"))
        
        self.action_text.setText(_translate("main_window", "Text"))
        self.action_text.setShortcut(_translate("main_window", "Ctrl+T"))
