# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file ''
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_window(object):

    def setupUi(self, main_window) -> None:

        main_window.setObjectName("main_window")
        main_window.resize(400, 200)

        self.central_widget = QtWidgets.QWidget(main_window)
        self.central_widget.setObjectName("central_widget")
        main_window.setCentralWidget(self.central_widget)

        self.line_edit_1 = QtWidgets.QLineEdit(self.central_widget)
        self.line_edit_1.setGeometry(QtCore.QRect(20, 10, 110, 20))
        self.line_edit_1.setFrame(True)
        self.line_edit_1.setObjectName("line_edit_1")

        self.line_edit_2 = QtWidgets.QLineEdit(self.central_widget)
        self.line_edit_2.setGeometry(QtCore.QRect(20, 40, 110, 20))
        self.line_edit_2.setObjectName("line_edit_2")

        self.line_edit_3 = QtWidgets.QLineEdit(self.central_widget)
        self.line_edit_3.setGeometry(QtCore.QRect(20, 70, 110, 20))
        self.line_edit_3.setObjectName("line_edit_3")

        self.line_edit_4 = QtWidgets.QLineEdit(self.central_widget)
        self.line_edit_4.setGeometry(QtCore.QRect(20, 100, 110, 20))
        self.line_edit_4.setInputMask("")
        self.line_edit_4.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.line_edit_4.setObjectName("line_edit_4")

        self.line_edit_5 = QtWidgets.QLineEdit(self.central_widget)
        self.line_edit_5.setGeometry(QtCore.QRect(20, 130, 110, 20))
        self.line_edit_5.setInputMask("")
        self.line_edit_5.setMaxLength(8)
        self.line_edit_5.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.line_edit_5.setDragEnabled(True)
        self.line_edit_5.setObjectName("line_edit_5")

        self.line_edit_6 = QtWidgets.QLineEdit(self.central_widget)
        self.line_edit_6.setGeometry(QtCore.QRect(20, 160, 110, 20))
        self.line_edit_6.setInputMask("")
        self.line_edit_6.setMaxLength(8)
        self.line_edit_6.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.line_edit_6.setDragEnabled(False)
        self.line_edit_6.setObjectName("line_edit_6")

        self.read_only_line_edit = QtWidgets.QLineEdit(self.central_widget)
        self.read_only_line_edit.setGeometry(QtCore.QRect(20, 190, 110, 20))
        self.read_only_line_edit.setInputMask("")
        self.read_only_line_edit.setMaxLength(8)
        self.read_only_line_edit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.read_only_line_edit.setDragEnabled(False)
        self.read_only_line_edit.setReadOnly(True)
        self.read_only_line_edit.setObjectName("read_only_line_edit")

        self.placeholder_text_line_edit_1 = QtWidgets.QLineEdit(self.central_widget)
        self.placeholder_text_line_edit_1.setGeometry(QtCore.QRect(190, 10, 110, 20))
        self.placeholder_text_line_edit_1.setInputMask("")
        self.placeholder_text_line_edit_1.setMaxLength(10000)
        self.placeholder_text_line_edit_1.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.placeholder_text_line_edit_1.setDragEnabled(False)
        self.placeholder_text_line_edit_1.setReadOnly(False)
        self.placeholder_text_line_edit_1.setObjectName("placeholder_text_line_edit_1")

        self.placeholder_text_line_edit_2 = QtWidgets.QLineEdit(self.central_widget)
        self.placeholder_text_line_edit_2.setGeometry(QtCore.QRect(190, 40, 110, 20))
        self.placeholder_text_line_edit_2.setInputMask("")
        self.placeholder_text_line_edit_2.setMaxLength(10000)
        self.placeholder_text_line_edit_2.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.placeholder_text_line_edit_2.setDragEnabled(False)
        self.placeholder_text_line_edit_2.setReadOnly(False)
        self.placeholder_text_line_edit_2.setClearButtonEnabled(True)
        self.placeholder_text_line_edit_2.setObjectName("placeholder_text_line_edit_2")

        self.menu_bar = QtWidgets.QMenuBar(main_window)
        self.menu_bar.setGeometry(QtCore.QRect(0, 0, 489, 21))
        self.menu_bar.setObjectName("menu_bar")
        main_window.setMenuBar(self.menu_bar)

        self.status_bar = QtWidgets.QStatusBar(main_window)
        self.status_bar.setObjectName("status_bar")
        main_window.setStatusBar(self.status_bar)

        self.retranslateUi(main_window)

        QtCore.QMetaObject.connectSlotsByName(main_window)


    def retranslateUi(self, main_window) -> None:
        _translate = QtCore.QCoreApplication.translate

        main_window.setWindowTitle(_translate("main_window", "Main Window"))

        self.line_edit_1.setInputMask(_translate("main_window", ">AAAAAAA"))
        self.line_edit_2.setInputMask(_translate("main_window", ">AAAA-AAAA"))
        self.line_edit_3.setInputMask(_translate("main_window", ">\\[AAAA\\]-\\(AAAA\\)"))

        self.placeholder_text_line_edit_1.setPlaceholderText(_translate("main_window", "Insert your text"))
        self.placeholder_text_line_edit_2.setPlaceholderText(_translate("main_window", "Insert your text"))
