# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file ''
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_window(object):

    def setupUi(self, main_window) -> None:
        
        main_window.setObjectName("main_window")
        main_window.resize(400, 200)

        self.central_widget = QtWidgets.QWidget(main_window)
        self.central_widget.setObjectName("central_widget")
        main_window.setCentralWidget(self.central_widget)

        self.push_button_paste = QtWidgets.QPushButton(self.central_widget)
        self.push_button_paste.setGeometry(QtCore.QRect(170, 100, 101, 23))
        self.push_button_paste.setObjectName("push_button_paste")

        self.push_button_copy = QtWidgets.QPushButton(self.central_widget)
        self.push_button_copy.setGeometry(QtCore.QRect(170, 40, 101, 23))
        self.push_button_copy.setObjectName("push_button_copy")

        self.line_edit_insert = QtWidgets.QLineEdit(self.central_widget)
        self.line_edit_insert.setGeometry(QtCore.QRect(40, 40, 113, 20))
        self.line_edit_insert.setObjectName("line_edit_insert")

        self.line_edit_paste = QtWidgets.QLineEdit(self.central_widget)
        self.line_edit_paste.setGeometry(QtCore.QRect(40, 100, 113, 20))
        self.line_edit_paste.setObjectName("line_edit_paste")

        self.status_bar = QtWidgets.QStatusBar(main_window)
        self.status_bar.setObjectName("status_bar")
        main_window.setStatusBar(self.status_bar)

        self.retranslateUi(main_window)

        self.push_button_copy.released.connect(self.line_edit_insert.copy) # type: ignore
        self.push_button_copy.pressed.connect(self.line_edit_insert.selectAll) # type: ignore
        self.push_button_paste.clicked.connect(self.line_edit_paste.paste) # type: ignore

        # NOTE: Not needed, sice all button were conected previously
        QtCore.QMetaObject.connectSlotsByName(main_window)


    def retranslateUi(self, main_window) -> None:
        _translate = QtCore.QCoreApplication.translate

        main_window.setWindowTitle(_translate("main_window", "Main Window"))
        
        self.push_button_paste.setText(_translate("main_window", "Paste"))
        self.push_button_copy.setText(_translate("main_window", "Copy and Select"))
